[package]
name = "kilojoule"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "14.0.0"
base64 = "0.22.1"
serde_json = "1.0.116"
toml = "0.8.13"
