[package]
name = "kilojoule_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
once_cell = "1.19.0"
regex = "1.10.4"
rustyline = "14.0.0"
serde_json = "1.0.116"
toml = "0.8.13"
